version: "3.8"

services:
    redis:
        image: redis:6.2.6-alpine
        ports:
            - 6389:6379
        command: redis-server /usr/local/etc/redis/redis.conf
        networks:
            - my-bridge-network
        volumes:
            - /appdata/docker/redis:/data
            - /appdata/docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
        restart: always
networks:
    my-bridge-network:
        external: true