version: "3"

services:
  jenkins:
    container_name: dood-jenkins
    image: dood-jenkins
    environment:
      - TZ=Asia/Seoul
      - JENKINS_OPTS=--httpPort=8081
    ports:
      - 8081:8081
    volumes:
      - /appdata/docker/dood-jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - my-bridge-network
    user: jenkins